#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$PGSQL_USER" <<-EOSQL
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
	CREATE USER $APP_PGSQL_USER WITH PASSWORD '$APP_PGSQL_PASSWORD';

	-- create db
	CREATE DATABASE $PGSQL_DATABASE;
	SET search_path=$PGSQL_DATABASE;
	GRANT ALL PRIVILEGES ON DATABASE $PGSQL_DATABASE TO $APP_PGSQL_USER;
	ALTER DEFAULT PRIVILEGES FOR USER $APP_PGSQL_USER IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $APP_PGSQL_USER;
	ALTER DEFAULT PRIVILEGES FOR USER $APP_PGSQL_USER IN SCHEMA public GRANT ALL ON SEQUENCES TO $APP_PGSQL_USER;
	GRANT SELECT, INSERT, UPDATE, DELETE PRIVILEGES ON ALL TABLES IN SCHEMA public TO $APP_PGSQL_USER;
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $APP_PGSQL_USER;

  -- create testdb
	CREATE DATABASE $TEST_PGSQL_DATABASE;
  SET search_path=$TEST_PGSQL_DATABASE;
  GRANT ALL PRIVILEGES ON DATABASE $TEST_PGSQL_DATABASE TO $APP_PGSQL_USER;
  ALTER DEFAULT PRIVILEGES FOR USER $APP_PGSQL_USER IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $APP_PGSQL_USER;
  ALTER DEFAULT PRIVILEGES FOR USER $APP_PGSQL_USER IN SCHEMA public GRANT ALL ON SEQUENCES TO $APP_PGSQL_USER;
  GRANT SELECT, INSERT, UPDATE, DELETE PRIVILEGES ON ALL TABLES IN SCHEMA public TO $APP_PGSQL_USER;
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $APP_PGSQL_USER;
EOSQL

# you need to give execution permission to your script file, since Docker copies over permissions
# chmod +x .docker/pgsql/init.sh